# Generated by Django 3.0.14 on 2021-11-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211120_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='img_url',
        ),
    ]
