# Generated by Django 3.0.14 on 2021-11-21 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211120_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='bids',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
