# Generated by Django 3.0.14 on 2021-11-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211121_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='img_url',
            new_name='image',
        ),
    ]
