# Generated by Django 3.0.14 on 2021-11-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211121_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='img_url',
        ),
    ]
